export const PUT_INGREDIENTS: "PUT_INGREDIENTS" = "PUT_INGREDIENTS";
export const PUT_BUN: "PUT_BUN" = "PUT_BUN";
export const CLEAR_CONSTRUCTOR: "CLEAR_CONSTRUCTOR" = "CLEAR_CONSTRUCTOR";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const MOVE_INGREDIENT: "MOVE_INGREDIENT" = "MOVE_INGREDIENT";


export const SET_CURRENT_INGREDIENT: 'SET_CURRENT_INGREDIENT' = 'SET_CURRENT_INGREDIENT';
export const CLEAR_CURRENT_INGREDIENT: "CLEAR_CURRENT_INGREDIENT" = "CLEAR_CURRENT_INGREDIENT";


export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" = "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" = "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_ERROR: "GET_INGREDIENTS_ERROR" = "GET_INGREDIENTS_ERROR";


export const CLOSE_MODAL: "CLOSE_MODAL" = "CLOSE_MODAL"
export const OPEN_MODAL: "OPEN_MODAL" = "OPEN_MODAL"


export const SET_NUMBER_ORDER_REQUEST: "SET_NUMBER_ORDER_REQUEST" = "SET_NUMBER_ORDER_REQUEST";
export const SET_NUMBER_ORDER_SUCCESS: "SET_NUMBER_ORDER_SUCCESS" = "SET_NUMBER_ORDER_SUCCESS";
export const SET_NUMBER_ORDER_ERROR: "SET_NUMBER_ORDER_ERROR" = "SET_NUMBER_ORDER_ERROR";


export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_FAILED: 'GET_ORDER_FAILED' = 'GET_ORDER_FAILED';

export const SET_AUTH_CHECKED: "SET_AUTH_CHECKED" = "SET_AUTH_CHECKED";
export const SET_USER: "SET_USER" = "SET_USER";

export const USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST" = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS" = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_ERROR: "USER_UPDATE_ERROR" = "USER_UPDATE_ERROR";
export const UPDATE_USER_AUTH: "UPDATE_USER_AUTH" = "UPDATE_USER_AUTH";

export const USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST" = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS" = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR: "USER_LOGIN_ERROR" = "USER_LOGIN_ERROR";

export const USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST" = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS" = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_ERROR: "USER_REGISTER_ERROR" = "USER_REGISTER_ERROR";

export const USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST" = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS" = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_ERROR: "USER_LOGOUT_ERROR" = "USER_LOGOUT_ERROR";


export const WS_CONNECTION_START: 'WS_CONNECTION_START' = 'WS_CONNECTION_START';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' = 'WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' = 'WS_CONNECTION_CLOSED';
export const WS_GET_ORDERS: 'WS_GET_ORDERS' = 'WS_GET_ORDERS';